#default_language_version:
#  # default language version for each language
#  python: python3.9
#repos:
#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.4.0
#    hooks:
#      - id: check-ast
#      - id: check-case-conflict
#      - id: check-executables-have-shebangs
#      - id: check-merge-conflict
#      - id: debug-statements
#      - id: end-of-file-fixer
#      - id: name-tests-test
#        args: [ "--django" ]
#      - id: trailing-whitespace
#
##  - repo: https://github.com/pycqa/bandit
##    rev: 1.7.4
##    hooks:
##      - id: bandit
##        args: ['-iii', '-ll']
#  - repo: https://github.com/pycqa/pylint
#    rev: "v2.16.2"
#    hooks:
#      - id: pylint
#        exclude: "[a-zA-Z]*/(migrations)/(.)*"
#        args: [ "--load-plugins=pylint_django", "--django-settings-module=pokerleaderboard.settings" ]
#        additional_dependencies: [
#          # pylint dependency
#            pylint_django,
#          # runtime dependencies
#            ...
#        ]
