# Generated by Django 4.1.7 on 2023-03-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_alter_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
    ]
